<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KelasSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // 5 Data Tahun 2024 - Periode Ganjil
            [
                'kode_kelas' => '20241-INF01',
                'nama_matakuliah' => 'Pemrograman Web Lanjut',
                'jumlah_sks' => '3',
                'periode' => 'Ganjil',
                'tahun_ajaran' => '2026',
                'semester' => '5',
                'hari' => 'Senin',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '10:30:00',
                'ruangan' => 'Lab Komputer 1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kelas' => '20241-INF02',
                'nama_matakuliah' => 'Basis Data Terstruktur',
                'jumlah_sks' => '3',
                'periode' => 'Ganjil',
                'tahun_ajaran' => '2026',
                'semester' => '3',
                'hari' => 'Selasa',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:30:00',
                'ruangan' => 'Ruang 302',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kelas' => '20241-INF03',
                'nama_matakuliah' => 'Struktur Data',
                'jumlah_sks' => '4',
                'periode' => 'Ganjil',
                'tahun_ajaran' => '2026',
                'semester' => '3',
                'hari' => 'Rabu',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '11:20:00',
                'ruangan' => 'Lab Komputer 2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kelas' => '20241-INF04',
                'nama_matakuliah' => 'Kecerdasan Buatan',
                'jumlah_sks' => '3',
                'periode' => 'Ganjil',
                'tahun_ajaran' => '2026',
                'semester' => '7',
                'hari' => 'Kamis',
                'jam_mulai' => '10:00:00',
                'jam_selesai' => '12:30:00',
                'ruangan' => 'Ruang 405',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kelas' => '20241-INF05',
                'nama_matakuliah' => 'Jaringan Komputer',
                'jumlah_sks' => '3',
                'periode' => 'Ganjil',
                'tahun_ajaran' => '2026',
                'semester' => '5',
                'hari' => 'Jumat',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '10:30:00',
                'ruangan' => 'Lab Jaringan',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 5 Data Tahun 2023 - Periode Genap
            [
                'kode_kelas' => '20232-INF01',
                'nama_matakuliah' => 'Algoritma & Pemrograman',
                'jumlah_sks' => '4',
                'periode' => 'Genap',
                'tahun_ajaran' => '2023',
                'semester' => '2',
                'hari' => 'Senin',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '11:20:00',
                'ruangan' => 'Lab Komputer 1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kelas' => '20232-INF02',
                'nama_matakuliah' => 'Interaksi Manusia & Komputer',
                'jumlah_sks' => '2',
                'periode' => 'Genap',
                'tahun_ajaran' => '2023',
                'semester' => '4',
                'hari' => 'Selasa',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '09:40:00',
                'ruangan' => 'Ruang 201',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kelas' => '20232-INF03',
                'nama_matakuliah' => 'Sistem Operasi',
                'jumlah_sks' => '3',
                'periode' => 'Genap',
                'tahun_ajaran' => '2023',
                'semester' => '4',
                'hari' => 'Rabu',
                'jam_mulai' => '13:00:00',
                'jam_selesai' => '15:30:00',
                'ruangan' => 'Ruang 301',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kelas' => '20232-INF04',
                'nama_matakuliah' => 'Etika Profesi',
                'jumlah_sks' => '2',
                'periode' => 'Genap',
                'tahun_ajaran' => '2023',
                'semester' => '6',
                'hari' => 'Kamis',
                'jam_mulai' => '08:00:00',
                'jam_selesai' => '09:40:00',
                'ruangan' => 'Ruang 105',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_kelas' => '20232-INF05',
                'nama_matakuliah' => 'Mobile Programming',
                'jumlah_sks' => '3',
                'periode' => 'Genap',
                'tahun_ajaran' => '2023',
                'semester' => '6',
                'hari' => 'Jumat',
                'jam_mulai' => '13:30:00',
                'jam_selesai' => '16:00:00',
                'ruangan' => 'Lab Komputer 3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('kelas')->insert($data);
    }
}